service: chatbot
image: example/chatbot

servers:
  web:
    hosts:
      - xxx
    labels:
      traefik.http.routers.hey-web.entrypoints: websecure
      traefik.http.routers.hey-web.rule: Host(`chatbot.example.com`)
      traefik.http.routers.hey-web.tls.certresolver: letsencrypt

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_TOKEN

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    APP_ENV: production
  secret:
    - ROOM_URL

builder:
  multiarch: <%= RUBY_PLATFORM != "x86_64-linux" %>

ssh:
  user: ubuntu

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "your-email@example.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web
